import { Calendar } from '../model/calendar';

export const calendarData: Calendar = {
  '1': {
    title: 'DODONGO',
    link: 'https://louiezong.bandcamp.com/album/dodongo',
    description: [
      "Parfois il y a des fan-création qui semblent tomber sous le sens. Des reprises qui sont tellement naturelles, c'est comme si les œuvres d'origines avaient été créées pour elles ! Il devient alors impossible de revenir à l'ancien sans les percevoir. L'original et le dérivé se complémentent l'un et l'autre, ne formant plus qu'un seul corpus.",
      "DODONGO est un album reprenant des compositions des jeux *Zelda* dans le style du groupe *RATATAT*. Un mariage étonnamment parfait, qui n'attendait qu'un compositeur pour le découvrir. Il aurait été facile de reprendre le thème principal de la saga, et de le jouer avec l'instrumentation du groupe, en y mélangeant quelques phrases connues histoire de. À la place, DODONGO adapte des morceaux savamment choisis qui lui permettent de capturer avec justesse l'identité de *RATATAT* tout en ayant leur propre cachet. Le résultat est surprenant, désarçonnant avec des mélodies et des styles familiers qui se retrouvent transformés en quelque chose de complètement nouveau.",
      "N'hésitez pas au passage à parcourir la discographie de *Louie Zong* ! C'est un artiste que j'ai découvert cette année, et dont beaucoup de ses (nombreuses) création musicales mettent instantanément le sourire aux lèvres.",
    ],
    videoUrl: 'https://www.youtube.com/embed/Iqp5AerPC9c',
  },
  '2': {
    title: 'A Fox in Space',
    description: [
      "Vous vous souvenez de Star Fox ? Je suis assez étonné que le potentiel narratif de cette série n'ait jamais été vraiment exploité par Nintendo. *Star Fox 64* est un « bête » jeu de tir, mais il s'en dégage l'énergie d'un cartoon jeunesse des 90 (que l'on doit en partie à la série *Thunderbirds*, lui ayant servi d'inspiration) ! En très peu de dialogues, le jeu parvient à construire des personnages aux personnalités prononcés, et un univers qui donne envie d'être exploré. Mais faute de projet concrets pour en faire une sérieuse franchise, c'est finalement le public qui se l'est ré-approprié.",
      "La technique méticuleuse de A Fox in Space me bluffe toujours. Que ce soit par le style, les couleurs, l'animation, même le son : l'illusion d'une série d'animation des 80s est parfaite. C'est comme ouvrir une fenêtre sur une réalité alternative, où Star Fox aurait toujours existé sous cette forme. Il faut dire que le scénario space-opera un peu kitsch des jeux s'y prête à merveille. Une partie de moi est curieuse de voir ce que donnerait ce projet s'il allait plus loin. Mais l'autre souhaite le laisser dans l'imaginaire. Celui d'une série qui n'a jamais existé, mais qui renvoie à tant d'autres.",
    ],
    videoUrl: 'https://www.youtube.com/embed/uieM18rZdHY',
  },
  '3': {
    title: 'Noclip',
    link: 'https://noclip.website',
    description: [
      "N'avez-vous jamais souhaité voir un niveau de jeu au-delà de ce que la caméra peut atteindre ? Si oui, Noclip est fait pour vous ! Ce site web permet de visualisés les modèles 3Ds de maps exportés directement depuis une riche galerie de jeux. Celle-ci allant de la Nintendo 64 à la Wii, en passant par quelques jeux PC et même quelques titres récents ! C'est un formidable outil pour mieux comprendre la construction de niveaux, aussi bien sur le plan technique que level-design. Certains jeux disposent même des animations sur leurs modèle ! Le travail de rétro-ingénierie accompli par Jasper, développeur derrière Noclip, force le respect.",
      "C'est aussi une manière géniale de se promener dans ces décors ! Je peux passer des heures à parcourir ces zones de jeux, les inspecter pour mieux les comprendre, profiter de panoramas inédits et de point de vue d'ensemble de ces mondes… C'est un bonheur que de redécouvrir des lieux familiers depuis des vues aériennes ! Et c'est aussi génial pour l'édition vidéo. Cerise sur le gâteau, le mode Studio donne même la possibilité d'enregistrer des mouvements de caméra, pour des travellings spectaculaires !",
      "Je ne peux que vous conseiller les map de Mario Kart 8, aux décors beaucoup trop soignés pour un jeu de course. Ou encore celles de Super Smash Bros. Brawl, permettant de comprendre comment fonctionnent les animations de certains terrains ! Et bien sûr, ne manquez pas de faire un détour par les cartes de Dark Souls, aux proportions époustouflantes. Vous pouvez sinon opter pour la sélection d'une map random, vous tomberez certainement sur quelque chose d'intéressant !",
    ],
    imgUrl: '/img/noclip_coconut.png',
  },
  '4': {
    title: 'Le Dernier Secret de Shadow of the Colossus',
    link: 'https://archive.org/details/shadow-of-the-colossus-quest-for-the-last-big-secret-ps-2-forums-full/',
    description: [
      "Le 26 décembre 2007, 2 ans après la sortie de Shadow of the Colossus, un topic est ouvert sur un forum (bienvenue dans les années 2000) suggérant la théorie qu'un dernier secret encore non trouvé dans le jeu. Une théorie si convaincante qu'elle entraînera une chasse au trésor longue de près de dix ans ! Cet incroyable récit aurait tout à fait eu sa place dans un épisode de Side Web. C'est un magnifique exemple d'une communauté dédiée à faire vivre un jeu au-delà de l'œuvre elle-même. À l'analyser sous tous ses angles, décrire des parallèles avec d'autres contes et mythologies, voire en faire de l'analyse littéraire. Cette quête a résulté en une cartographie du jeu si exhaustive et précise que que les travaux en résultants ont été réutilisés en 2017 par Bluepoint pour le développement du remake. Car la culture n'est jamais uni-directionnel, je trouve toujours formidable lorsque des échanges se créent entre les créateurs et l'audience, avec des impacts positifs sur l'œuvre originale. Shadow of the Colossus est un jeu incroyable, et sa communauté l'est tout autant.",
    ],
    videoUrl: 'https://www.youtube.com/embed/nZbXHjimmZI',
  },
  '5': {
    title: 'Another Metroid 2 Remake',
    link: '',
    description: [
      "AM2R est un des fan-game les plus impressionant que je connaisse. Développé sur plusieurs années exclusivement sur du temps libre, dirigé par une seule personne, avec pour ambition de faire un remake de l'intégralité du jeu GB Metroid II. Et pas seulement une refonte graphique : le jeu profite aussi des capacités techniques plus élevées pour mettre davantage l'accent sur l'action et l'exploration. Une revisite complète du game-design original ! Et le plus fou dans ce projet ambitieux, c'est qu'il a abouti à un excellent jeu. Non seulement il est visuellement et musicalement beau et varié, mais de prime il est aussi très fun parcourir ! Honnêtement ce jeu s’intégrerait très bien à la saga officielle tant il est soigné.",
      "Mais Nintendo n'a pas été de cet avis. Sitôt sorti, le jeu s'est fait retiré de la toile pour violation de copyright. Peut-être par crainte de concurrence avec l'autre remake officiel de Metroid 2, Samus Returns ? Ou plus probablement parce que Nintendo est exagérément strict avec ses licences. Ce qui est regrettable, car l'expression créatrice du public devrait avoir une place légitime dans la culture. En témoigne AM2R qui est justement une proposition intéressante sur Metroid II, de part ses différences avec aussi bien l'original que Samus Returns sur 3DS !",
      "Je ne peux donc que vous recommander d'y jouer. Malheureusement on entame la catégorie du contenu disparu d'internet. Mais AM2R n'est vraiment pas difficile à retrouver, pour peu que l'on cherche. Je peux même vous donner une piste : saviez-vous que *Internet Archive*, le collectif de sauvegarde du web, possède une rubrique *Software* ? Et si vous recherchez quelque chose de plus court, jetez un coup d'œil à *Skippy the Bot* du même créateur. Un spin-off particulier à maîtriser, mais au level-design diablement ingénieux !",
    ],
    imgUrl: '/img/am2r.png',
  },
  '6': {
    title: 'Line Them Up!',
    description: [
      "Je n'en avais pas fini avec Origami King ! Si vous avez vu ma vidéo sur le jeu, vous avez dû deviner que j'aime beaucoup ses musiques. Les compositions ont cela de remarquable qu'elles sont souvent inattendues, surtout pour un jeu Nintendo. Un village dans un désert va utiliser de l'éléctro mélangé à du jazz, dans un temple on va croiser de l'euro-dance, on retrouve même un remix d'une piste de Mario Kart Wii ! C'est bourré de choix créatifs, un véritable délice en parcourant le jeu.",
      "C'est donc également un bonheur d'entendre les arrangements d'autres musiciens ! Mais pas sous n'importe quel forme ici, puisqu'il s'agit d'un concert. Diffusé lors du *vgmtogether* 2021, un événement en ligne consacré à la musique de jeu-vidéo. La date n'est pas anodine : beaucoup de pays étaient encore confinés, et les conventions ou n'importe quel autre événement étaient hors de l'équation ! Ce fut donc un réel bulle d'oxygène de pouvoir voir des *vrais* musiciens jouer, même au travers d'un écran. Certes, il n'y avait pas de scène, et toutes les performances étaient enregistrées. Mais ce format permet malgré tout de mettre en valeur l'humain, de montrer chaque artiste un à un, chacun ajoutant sa propre mise en scène. Le montage en profite même pour être créatif, et créer un véritable spectacle à partir de ces performances !",
      "Ce concert vaut donc carrément d'être visionné en plus qu'écouté. On y retrouve des musiciens talentueux (dont certains \"grand\" noms, comme entre autre Lena Raine, David Wise, Carlos Eiene…) performant des reprises de qualité au sein d'un très bon spectacle. Une merveilleuse création collective !",
    ],
    videoUrl: 'https://www.youtube.com/embed/zCXrspb-qLg',
  },
  '7': {
    title: 'Half Life in 60 seconds',
    description: [
      "Vous pensiez bien que ce calendrier allait être nostalgique ! Side Web, c'est aussi l'occasion de déterrer des animations Flash des années 2000. Celle-ci date de 2007, et je la connais encore par cœur. Je n'ai pourtant jamais joué à aucun Half-Life. À vrai dire même aujourd'hui, je peine à comprendre tout ce qu'il se passe dans cette vidéo. Mais y a pas besoin je crois. Le rythme absurde auquel s'enchaînent les scènes et le charme des bruitages maisons sont largement suffisant pour apprécier !",
      "C'est carrément kitsch, mais pour être honnête, je pense que cette animation fait partie de celles de l'époque qui ont le mieux vieilli. En grande partie parce que c'est une des rares à ne pas plonger dans de l'humour sexiste ou homophobe (oui, c'est un triste constat, mais le web des années 2000 est un terrain miné à ce niveau). Non, à la place ses gags sont purement crétins, jouant de manière puérile avec la mise en scène ou la répétition. Et aujourd'hui, bah je trouve que ça marche encore ! De manière bancale okay, mais ça fait mouche quand même.",
      "Dans la large culture de l'animation, ce court-métrage n'est certainement pas glorieux. Mais je suis content de savoir que, même après ne plus y avoir pensé pendant plus d'une décennie, il était resté quelque part dans un coin de mon cerveau. Blablabla Mister Freeman.",
    ],
    videoUrl: 'https://www.youtube.com/embed/slRsexrhbG8',
  },
  '8': {
    title: 'Nintendo On',
    description: [
      "2005, Nintendo s'apprête à dévoiler à l'E3 sa prochaine console, le fameux projet « Révolution ». Mais quelques semaines avant l'événement, voilà qu'un leak apparaît sur la toile : le trailer du *Nintendo ON* ! Démarrant sur une rétrospective des anciennes consoles, puis une démo technique élégante sur un niveau de Mario 64, il marque les esprits par une annonce complètement folle : Le Nintendo ON sera un casque de réalité virtuelle ! À l'époque où l'on n'utilisait même pas le terme « VR », Nintendo nous promettait un casque sans fil, plus puissant que n'importe quelle autre console du marché ! Peu de temps avant que la vidéo ne coupe abruptement, on a tout juste le temps d'apercevoir des images exclusives d'un prochain Metroid 3D, et même un Mario HD ! Cette vidéo est-elle officielle ? Une bonne partie de l'internet y croit, car la réalisation est de beaucoup trop bonne qualité pour que ce soit un fake, non ?",
      "Bien sûr on réalise très vite que c'en est un. Nintendo ne tarde pas à introduire la Wii, qui même si elle innove sur le plan du motion-control, ne propose aucune sorte de réalité virtuelle. Pour autant, je ne pense pas qu'on ait oublié ce trailer légendaire. Est-ce qu'un fake rentre dans la catégorie des fan-création ? Difficile à dire, mais dans le cas de la Nintendo ON, il faut tout de même souligner que ce trailer a été réalisé par une seule personne sur son temps libre, Pablo Delmonte. À une époque où il n'était pas aussi facile qu'aujourd'hui de l'animation 3D ! Le travail est simplement bluffant de crédulité, tant tout y est soigné. On retrouve même une certaine fidélité à la charte graphique Nintendo de l'époque, dans la continuité de la Nintendo DS, et le sobre épuré de la Wii qui allait suivre.",
      "Bien sûr un terme de prédiction, la Nintendo ON était bien à côté de la plaque. Nintendo n'allait jamais cibler le public gamer aussi spécifiquement, ni viser la puissance graphique. La VR telle qu'elle est présentée ici correspond avant tout aux fantasmes existant depuis les années 80, loin de qu'elle proposera quinze ans après. Et ne parlons pas du design carrément maladroit de Mario ! Malgré tout, ce faux trailer est devenu une petite légende. Et je ne pense pas être le seul à me remémorer avec nostalgies ce champ infini de châteaux, et les rêves si prometteurs qu'il nous a transmis.",
    ],
    videoUrl: 'https://www.youtube.com//embed/zX2smM87r14',
  },
  '9': {
    title: 'POTTERGAME',
    link: 'https://www.glorioustrainwrecks.com/node/11931',
    description: [
      "Si vous ne le saviez pas déjà, Harry Potter, c'est canceled. Au-delà de la transphobie gerbante de Rowling, le récit lui-même est aussi problématique sur plusieurs points. Il traduit globalement un progressisme assez hypocrite, qui se focalise surtout sur les actions individuelles, en maintenant sagement le statu quo. Les Serpentards sont des bourgeois fachos, mais c'est leur droit, vous voyez. Et à côté il y a aussi les jeux-vidéo Harry Potter, qui eux aussi se sont fait épingler par effet de bord des harcèlement sexuels du compositeur Jérémy Soule. Sans parler du crunch classique de la part d'EA quand il s'agit de sortir un jeu en même temps que le film, vous vous en doutez bien. Vraiment Harry Potter, c'est pas une licence que j'ai envie de célébrer.",
      "Malgré tout, ce serait mentir que de prétendre que je n'ai pas grandi avec ces œuvres, dont les premier jeux-vidéo Harry Potter. Des jeux plutôt ambitieux pour des adaptations de film. Non mais vous avez vu les animations des sprites de la version Game Boy Color !? De mon côté c'est les versions PC que j'ai connues, et il s'en dégage toujours une certaine aura spéciale. Je suis forcément nostalgique de ce château que j'ai parcouru des dizaines de fois, ces Flipendo lancés et ces quêtes qui n'avaient aucun sens.",
      "POTTERGAME semble de prime abord retranscrire cette nostalgie. On y retrouve les modèles originaux des jeux, les textures, même l'agencement des salles ! De nouveau on nous envoie collecter des Dragées Surprises, sous des prétextes qui tiennent à peine debout. Le tout saupoudré d'un peu d'absurde et surréaliste, comme un hommage aux dialogues parfois bancals de ces jeux. Mais c'est alors qu'arrive un twist : ce qui n'était qu'une blague sur les toilettes des filles devient le centre du scénario, et le jeu passe alors à la satire complète. Questionnant l'esclavage au seine d'une école soi-disant progressive, attaquant Rowling sur ses propos, et parodiant même Ricky Gervais et la culture Britannique. Le château se déforme, les personnages deviennent si Brittish qu'ils se transforment en DVD de Love Actually… C'est une déconstruction totale de l'univers qui s'effectue !",
      "Alors évidemment, POTTERGAME n'est pas non plus une critique profonde de Harry Potter. C'est avant tout une farce satirique, un jeu décalé posté sur un forum. Mais en soi c'est une belle manière de faire ses au-revoir à la série. En se remémorant les souvenirs qu'on s'y est fait, et en n'ayant pas peur d'y pointer du doigt les défauts, au travers d'un absurde détaché.",
    ],
    imgUrl: '',
  },
  '10': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '11': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '12': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '13': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '14': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '15': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '16': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '17': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '18': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '19': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '20': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '21': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '22': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '23': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '24': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '25': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '26': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '27': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '28': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '29': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '30': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
  '31': {
    title: '',
    link: '',
    description: [],
    imgUrl: '',
    videoUrl: '',
  },
};
