name: Build and Deploy
on:
  push:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: |
          npm install
          npm run build
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: dist
